name: Reuse Matrix Workflow

on: [push, pull_request]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: s-weigand/gh-playground/.github/workflows/reusable-workflow.yml@reuse-matrix-workflow
